Alex2262/AltairChessEngine

search.cpp

```
ELO   | 8.62 +- 5.90 (95%)
GAMES | N: 7616 W: 2272 L: 2083 D: 3261
```
Bench: 9749098

futility pruning

---

constants.h
search.cpp
search.h

```
ELO   | 7.01 +- 5.11 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 10160 W: 3013 L: 2808 D: 4339
```
Bench: 8158913

scaling the initial aspiration window

---

search.cpp

```
ELO   | 13.79 +- 7.92 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4360 W: 1371 L: 1198 D: 1791
```

Qsearch see pruning

---

search.cpp

```
ELO   | 1.30 +- 2.02 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 65800 W: 19252 L: 19006 D: 27542
```
Bench: 8205216

Aspiration depth decreased when aspiration bounds fail

---

search.cpp

```
ELO   | 0.99 +- 3.13 (95%)
LLR   | -1.68 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 27000 W: 7781 L: 7704 D: 11515
```

Mate threat extensions

---

search.cpp

```
ELO   | 6.54 +- 4.88 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 11368 W: 3435 L: 3221 D: 4712
```

Passed extensions

---

search.cpp

```
ELO   | 3.37 +- 2.61 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 38936 W: 11393 L: 11015 D: 16528
```
Bench: 7983218

Stronger NMP conditions to prevent against zugzwang

---

position.cpp
position.h
search.cpp

```
ELO   | 1.93 +- 2.21 (95%)
LLR   | -0.24 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 52792 W: 14867 L: 14573 D: 23352
```
Bench: 15438777

Clear the state stack upon every new search

---

search.cpp

```
ELO   | 1.29 +- 2.00 (95%)
LLR   | -2.79 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 64464 W: 18121 L: 17882 D: 28461
```
Bench: 15988955

multicut pruning

---

search.cpp

```
ELO   | 3.65 +- 5.72 (95%)
LLR   | 2.98 (-2.94, 2.94) [-5.00, 1.00]
GAMES | N: 7896 W: 2248 L: 2165 D: 3483
```
Bench: 15448143

remove razoring

---

position.h
search.cpp

```
ELO   | 2.66 +- 3.78 (95%)
LLR   | 0.70 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 18040 W: 5106 L: 4968 D: 7966
```
Bench: 16780015

Double extensions & limiting extensions

---

search.cpp

```
ELO   | 0.65 +- 5.40 (95%)
LLR   | 1.26 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 8016 W: 2036 L: 2021 D: 3959
```
Bench: 14980203

Remove Mate Threat Extensions

---

search.h

```
ELO   | 3.24 +- 2.53 (95%)
GAMES | N: 40352 W: 11470 L: 11094 D: 17788
```

More noisy lmr

---

search.cpp

```
ELO   | 1.64 +- 1.86 (95%)
LLR   | -1.61 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 73928 W: 20668 L: 20319 D: 32941
```
Bench: 14168483

more history scores for pv or improving nodes

---

search.cpp
search.h

LTC
```
ELO   | 17.75 +- 8.68 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 3056 W: 837 L: 681 D: 1538
```
STC
```
ELO   | 20.14 +- 9.64 (95%)
GAMES | N: 2712 W: 814 L: 657 D: 1241
```

Node Count TM scaling

---

search.cpp

```
ELO   | 12.90 +- 7.49 (95%)
GAMES | N: 4472 W: 1295 L: 1129 D: 2048
```
Bench: 13865846

Allow reductions while in check but less aggressive

---

search.cpp

```
ELO   | -9.70 +- 7.61 (95%)
LLR   | -3.02 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4264 W: 1077 L: 1196 D: 1991
```
Loses 10 elo but needs to be fixed for other patches to take place
Bench: 15132877

Try fixing quiet pruning

---

evaluation.cpp
evaluation_constants.h

```
ELO   | 4.56 +- 3.60 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 19816 W: 5633 L: 5373 D: 8810
```
Bench: 12860638

Mobility arrays instead of multipliers

---

search.cpp

```
ELO   | 1.04 +- 2.18 (95%)
LLR   | -2.95 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 52496 W: 14231 L: 14074 D: 24191
```
Sort of a simplification patch
Bench: 13734555

Change check extension location

---

search.cpp

```
ELO   | 5.10 +- 3.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 15600 W: 4266 L: 4037 D: 7297
```
Bench: 13335871

Fewer reductions on interesting moves

---

search.cpp

```
ELO   | 4.36 +- 3.48 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 20552 W: 5668 L: 5410 D: 9474
```
Bench: 15609224

Clamp the LMR depth

---

search.cpp

```
ELO   | 17.87 +- 9.00 (95%)
GAMES | N: 3056 W: 894 L: 737 D: 1425
```
Bench: 15609224

Do not reset continuation history every move

---

search.cpp

```
ELO   | 2.52 +- 1.68 (95%)
GAMES | N: 87320 W: 23705 L: 23072 D: 40543
```
Bench: 13486598

Improving Heuristic for futility pruning

---

position.cpp
search.cpp
uci.cpp

```
ELO   | 4.83 +- 6.79 (95%)
LLR   | 2.97 (-2.94, 2.94) [-5.00, 3.00]
GAMES | N: 5464 W: 1524 L: 1448 D: 2492
```
Bench: 12356212

Possibly fix 50mr related issues

---

search.cpp
search.h

```
ELO   | 0.64 +- 2.56 (95%)
LLR   | -2.96 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 37336 W: 9902 L: 9833 D: 17601
https://chess.swehosting.se/test/1885/
```

favor pv nodes for replacement in TT

---

search.cpp

```
ELO   | 12.97 +- 7.52 (95%)
GAMES | N: 4448 W: 1291 L: 1125 D: 2032
https://chess.swehosting.se/test/1943/
```
Bench: 11841540

Let quiet LMP break out of the move loop

---

search.cpp

```
ELO   | 35.28 +- 17.09 (95%)
LLR   | 3.07 (-2.94, 2.94) [-7.00, 0.00]
GAMES | N: 1008 W: 367 L: 265 D: 376
https://chess.swehosting.se/test/2101/
```

Fix passed pawn extensions

---

search.cpp
search.h

```
ELO   | 4.43 +- 3.54 (95%)
GAMES | N: 19944 W: 5525 L: 5271 D: 9148
https://chess.swehosting.se/test/2189/
```
Bench: 11841540

Save best move on fail highs in aspiration window searches.

---

evaluation.cpp

```
ELO   | 3.37 +- 2.66 (95%)
GAMES | N: 35552 W: 9874 L: 9529 D: 16149
https://chess.swehosting.se/test/2244/
```
Bench: 12612058

move ordering changes

---

search.cpp

```
ELO   | 5.45 +- 4.21 (95%)
GAMES | N: 14080 W: 3911 L: 3690 D: 6479
https://chess.swehosting.se/test/2279/
```
Bench: 12612058

scale TM by score changes

---

search.cpp

```
ELO   | 3.35 +- 2.64 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 35368 W: 9610 L: 9269 D: 16489
https://chess.swehosting.se/test/2304/
```
Bench: 10053989

SEE pruning on pv nodes

---

evaluation.cpp
evaluation.h

```
ELO   | 1.66 +- 5.75 (95%)
LLR   | -0.12 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 7328 W: 1937 L: 1902 D: 3489
https://chess.swehosting.se/test/2462/
```
Bench: 9008298

OCB evaluation

---

search.cpp

easy original idea
```
ELO   | 4.07 +- 3.28 (95%)
GAMES | N: 22696 W: 6120 L: 5854 D: 10722
https://chess.swehosting.se/test/2639/
```

Null search no killers

---

search.cpp

```
ELO   | 10.44 +- 6.45 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 5728 W: 1561 L: 1389 D: 2778
https://chess.swehosting.se/test/2722/
```
Bench: 7891339

TT Fail low best move saving

---

evaluation.cpp

```
ELO   | 6.06 +- 4.55 (95%)
GAMES | N: 11992 W: 3328 L: 3119 D: 5545
https://chess.swehosting.se/test/3049/
```
Bench: 8813312

Actually adding backwards pawns

---

makefile

Before
```
$ ./Altair bench |tail -1
9025695 nodes 1530557 nps
$ ./Altair bench |tail -1
9025695 nodes 1515904 nps
$ ./Altair bench |tail -1
9025695 nodes 1528224 nps
```
After
```
$ ./Altair bench |tail -1
9025695 nodes 1851424 nps
$ ./Altair bench |tail -1
9025695 nodes 1855230 nps
$ ./Altair bench |tail -1
9025695 nodes 1801895 np
```

Build natively, if native=1 is passed to make

---

src/search.cpp

```
ELO   | 11.82 +- 7.07 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 4880 W: 1368 L: 1202 D: 2310
https://chess.swehosting.se/test/3452/
```
Bench: 7899460

NMP improving

---

makefile
src/constants.h
src/search.h

```
ELO: 1.89 +- 1.29 [0.607, 3.18]
LLR: 4.01 [0.0, 3.0] (-2.25, 2.89)
H1 Accepted
GAMES | N: 138192 W: 34571 L: 33822 D: 69799
https://chess.swehosting.se/test/3661/
```

Base capture margin

---

src/search.cpp

```
ELO   | 4.06 +- 3.26 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 21568 W: 5471 L: 5219 D: 10878
https://chess.swehosting.se/test/3871/
```

Aggressive bad capture

---

src/move_ordering.cpp
src/move_ordering.h
src/position.h
src/search.cpp
src/search.h

```
ELO   | 3.63 +- 2.92 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 27168 W: 6934 L: 6650 D: 13584
https://chess.swehosting.se/test/3942/
```
Free original idea
Bench: 8918856

Index capture history by whether a move is winning or losing

---

src/constants.h
src/search.cpp
src/search.h

```
ELO   | 12.85 +- 7.33 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 4192 W: 1097 L: 942 D: 2153
https://chess.swehosting.se/test/4376/
```

Remove delta pruning

---

src/nnue.cpp
src/search.cpp

```
ELO   | 2.21 +- 2.64 (95%)
LLR   | 0.80 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 31488 W: 7552 L: 7352 D: 16584
https://chess.swehosting.se/test/4390/
```
```
LLR: 3.93 [-3.0, 0.0] (-2.94, 2.94)
```
with regression/simplification bounds

Cleanup lmr

---

src/constants.h

```
ELO   | 4.14 +- 3.35 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 20288 W: 5105 L: 4863 D: 10320
https://chess.swehosting.se/test/4474/
```
Bench: 6215526

Add one more conthist move on 4th ply

---

src/search.cpp

Bench: 6620419
```
ELO   | 6.96 +- 5.01 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 9088 W: 2335 L: 2153 D: 4600
https://chess.swehosting.se/test/4612/
```

Verification search

---

src/search.cpp

```
ELO   | 4.05 +- 3.27 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 20144 W: 4810 L: 4575 D: 10759
https://chess.swehosting.se/test/5214/
```

Remove IID

---

src/search.cpp

STC:
```
Elo   | -4.83 +- 8.13 (95%)
LLR   | -1.55 (-2.25, 2.89) [0.00, 5.00]
Games | N: 3452 W: 827 L: 875 D: 1750
Penta | [49, 429, 798, 421, 29]
```
LTC:
```
Elo   | 2.56 +- 3.40 (95%)
LLR   | 1.80 (-2.25, 2.89) [0.00, 5.00]
Games | N: 17940 W: 4089 L: 3957 D: 9894
Penta | [86, 2015, 4626, 2167, 76]
```
Merged for scaling as time control increases

SE params changed

---

src/search.cpp

```
Elo   | 8.62 +- 6.33 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 5642 W: 1449 L: 1309 D: 2884
Penta | [57, 628, 1332, 726, 78]
```

Deeper / Shallower search

---

src/constants.h
src/search.cpp

STC
```
Elo   | 1.43 +- 1.76 (95%)
LLR   | -0.05 (-2.25, 2.89) [0.00, 5.00]
Games | N: 73502 W: 18165 L: 17863 D: 37474
Penta | [825, 8731, 17312, 9083, 800]
```
LTC
```
Elo   | 5.65 +- 4.97 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8424 W: 1960 L: 1823 D: 4641
Penta | [32, 925, 2182, 1020, 53]
http://antares2262.pythonanywhere.com/test/32/
```
LTC pass
Bench: 6603776

Change extension handling

---

src/search.cpp
src/search.h

```
Elo   | 1.90 +- 3.68 (95%)
LLR   | 0.58 (-2.25, 2.89) [0.00, 5.00]
Games | N: 16808 W: 4176 L: 4084 D: 8548
Penta | [184, 1960, 4021, 2058, 181]
ELO: 1.9 +- 3.68 [-1.78, 5.58]
LLR: 3.17 [-4.0, 1.0] (-2.94, 2.94)
```
Merged for cutnode functionality and non-regression
Bench: 7579896

Cutnode reductions

---

src/search.cpp

```
Elo   | 4.71 +- 4.22 (95%)
LLR   | 2.99 (-2.25, 2.89) [0.00, 5.00]
Games | N: 13132 W: 3404 L: 3226 D: 6502
Penta | [172, 1489, 3081, 1637, 187]
http://antares2262.pythonanywhere.com/test/60/
```

Negative Extensions on alpha condition in SE

---

src/search.cpp

```
Elo   | 3.41 +- 3.35 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 20288 W: 5088 L: 4889 D: 10311
Penta | [196, 2400, 4810, 2485, 253]
http://antares2262.pythonanywhere.com/test/68/
```
Bench: 6840903

move IIR after forward pruning

---

src/nnue.cpp
src/nnue.h

```
Elo   | 22.94 +- 10.97 (95%)
Games | N: 1896 W: 528 L: 403 D: 965
Penta | [15, 172, 461, 273, 27]
https://chess.swehosting.se/test/5708/
```
Bench: 8136981

Europa Net

---

CMakeLists.txt
makefile
src/nnue.cpp
src/search.h
src/timeman.cpp
src/timeman.h
src/uci.cpp
src/uci.h

Revamped Altair's time management.
STC:
```
Elo   | 5.53 +- 4.84 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 9430 W: 2325 L: 2175 D: 4930
Penta | [66, 1020, 2401, 1154, 74]
https://chess.swehosting.se/test/6143/
```
LTC:
```
Elo   | 9.22 +- 6.94 (95%)
Games | N: 4446 W: 1088 L: 970 D: 2388
Penta | [10, 445, 1202, 549, 17]
https://chess.swehosting.se/test/6148/
```
Cyclic TM:
```
Elo   | -2.39 +- 4.60 (95%)
SPRT  | 40/15.0+0.00s Threads=1 Hash=32MB
LLR   | -2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10026 W: 2268 L: 2337 D: 5421
Penta | [49, 1195, 2580, 1154, 35]
https://chess.swehosting.se/test/6167/
```
Although Cyclic TM did not gain, it had relatively …

Tm changes

---

src/search.cpp
src/search.h

Elo   | 3.91 +- 3.02 (95%)
Games | N: 15654 W: 3901 L: 3725 D: 8028
Penta | [138, 1764, 3846, 1942, 137]
https://chess.swehosting.se/test/7002/

qsearch TT eval

---

src/position.cpp

```
Elo   | -0.61 +- 3.33 (95%)
LLR   | 0.12 (-2.94, 2.94) [-4.00, 1.00]
Games | N: 10304 W: 2417 L: 2435 D: 5452
Penta | [34, 1157, 2773, 1169, 19]
https://chess.swehosting.se/test/7091/
```
Merged for being relatively equal at high game count while being a bug that is imperative to fix.

Fix pawn key

---

src/search.cpp

```
Elo   | 3.51 +- 2.77 (95%)
Games | N: 18980 W: 4776 L: 4584 D: 9620
Penta | [179, 2173, 4589, 2375, 174]
https://chess.swehosting.se/test/7139/
```

Qsearch pch

---

src/search.cpp
src/search.h

```
Elo   | 2.70 +- 2.16 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 29710 W: 7330 L: 7099 D: 15281
Penta | [228, 3452, 7241, 3729, 205]
https://chess.swehosting.se/test/7145/
```

Squared depth correction history

---

src/search.cpp

```
Elo   | 3.95 +- 3.04 (95%)
Games | N: 15674 W: 3943 L: 3765 D: 7966
Penta | [120, 1865, 3705, 2011, 136]
https://chess.swehosting.se/test/7169/
```

multicut use return eval

---

src/nnue.cpp
src/simd.h

Utilize NEON SIMD instead of auto vectorization now, after fixing instructions for `vec_int16_madd_int32`.
On my mac m1 air speedup is around:
`1.2Mnps` --> `1.3Mnps` 
From previous NEON SIMD to fixed NEON SIMD:
`0.9Mnps` --> `1.3Mnps`
The fix is most directly contributed by using `vpaddq_s32` which performs the horizontal addition, instead of the incorrect `vaddq_s32` which performs vertical, element-wise addition in `vec_int16_madd_int32`.

Fix NEON SIMD

---

src/search.h

SPSA tune at 6K iterations.
STC
```
Elo   | 12.29 +- 6.29 (95%)
Games | N: 3678 W: 946 L: 816 D: 1916
Penta | [22, 407, 871, 497, 42]
https://chess.swehosting.se/test/7407/
```
LTC ended early as it is wasting games. This should be gaining elo.
```
Elo   | 2.38 +- 2.81 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=128MB
LLR   | 1.38 (-2.94, 2.94) [0.00, 5.00]
Games | N: 14734 W: 3547 L: 3446 D: 7741
Penta | [34, 1658, 3883, 1757, 35]
https://chess.swehosting.se/test/7409/
```
Bench: 7754781

Tune 6000 iterations

---

src/search.h

Just another example that SPSA is not perfect. Values I chose myself gain more at LTC than a week+ long tune of ~100,000 LTC games.
```
Elo   | 4.50 +- 3.26 (95%)
Games | N: 11110 W: 2719 L: 2575 D: 5816
Penta | [26, 1232, 2905, 1356, 36]
https://chess.swehosting.se/test/7421/
```
Bench: 8014754

self chosen values

---

src/search.cpp

```
Elo   | 5.61 +- 3.85 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 9422 W: 2323 L: 2171 D: 4928
Penta | [73, 1044, 2330, 1186, 78]
https://chess.swehosting.se/test/7457/
```
Bench: 7467743

depth bonus to history

---

src/search.cpp

```
Elo   | 2.93 +- 2.96 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 25636 W: 6336 L: 6120 D: 13180
Penta | [143, 3010, 6337, 3144, 184]
```
Bench: 7611579

Fail Firm RFP

---

src/position.cpp

```
Elo   | 0.25 +- 3.10 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 23564 W: 5792 L: 5775 D: 11997
Penta | [135, 2781, 5941, 2782, 143]
http://antares2262.pythonanywhere.com/test/246/
```
Bench: 6828214

hash key fixes

---

src/search.cpp

```
Elo   | 2.98 +- 2.39 (95%)
Games | N: 23292 W: 5821 L: 5621 D: 11850
Penta | [148, 2629, 5913, 2787, 169]
https://chess.swehosting.se/test/9149/
```
Bench: 7316661

Remove Null Search Reduction
