- search.cpp
> aspiration windows changed

- .gitignore
- evaluation.cpp
- makefile
- move.cpp
- search.cpp
- uci.cpp
> I tried to resolve some warnings

- evaluation.cpp
- evaluation.h
- search.cpp
> Capture History in Qsearch

- position.h
- search.cpp
[SPRT Test](https://engineprogramming.pythonanywhere.com/test/224/)
```
ELO   | 2.81 +- 4.51 (95%)
LLR   | 0.60 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 12960 W: 3750 L: 3645 D: 5565
```
Bench: 11421198
> Move Gives Check stuff

- constants.h
- search.cpp
- search.h
- uci.cpp
Tuning search values with Weather Factory over 390K game.
```
ELO   | 10.24 +- 6.58 (95%)
GAMES | N: 6144 W: 1856 L: 1675 D: 2613
```
> Search tuning

- constants.h
- search.cpp
- search.h
```
ELO   | 18.63 +- 11.39 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 8.00]
GAMES | N: 2072 W: 655 L: 544 D: 873
```
Bench: 8467289
> copy Weiss ASP windows with some of Archi's values

- search.cpp
- see.cpp
- see.h
```
ELO   | 19.55 +- 9.65 (95%)
GAMES | N: 2864 W: 902 L: 741 D: 1221
```
> Pvs see pruning

- constants.h
- evaluation.cpp
- evaluation.h
- position.cpp
- position.h
- search.cpp
- search.h
- uci.cpp
Reverts Alex2262/AltairChessEngine#20
> Revert "Nmp zugwang"

- search.cpp
> reductions based TT moves and alpha fail counts

- search.cpp
> Internal Iterative Deepening

- constants.h
- search.cpp
- search.h
> Bad captures allowed in LMR

- position.cpp
- position.h
- search.cpp
```
ELO   | 6.82 +- 5.04 (95%)
GAMES | N: 10544 W: 3155 L: 2948 D: 4441
```
> NMP zugzwang

- search.cpp
```
ELO   | 1.18 +- 2.14 (95%)
LLR   | -2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 58184 W: 16843 L: 16645 D: 24696
```
Bench: 8035877
> Recaptures

- search.cpp
```
ELO   | 1.98 +- 4.69 (95%)
LLR   | -0.07 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 12312 W: 3635 L: 3565 D: 5112
```
> Check skip eval

- evaluation.cpp
```
ELO   | 4.25 +- 5.13 (95%)
LLR   | 1.31 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 10312 W: 3087 L: 2961 D: 4264
```
> See move ordering

- search.cpp
```
ELO   | 7.46 +- 14.24 (95%)
LLR   | 0.42 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 1304 W: 386 L: 358 D: 560
```
Bench: 8630297
> No returning TT hash score at pv nodes

- position.h
- search.cpp
```
ELO   | 7.11 +- 5.16 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 9976 W: 2965 L: 2761 D: 4250
```
Bench: 15119004
> Singular Extensions

- search.cpp
```
ELO   | 1.43 +- 3.70 (95%)
LLR   | 2.95 (-2.94, 2.94) [-4.00, 1.00]
GAMES | N: 18768 W: 5242 L: 5165 D: 8361
```
Bench: 15813939
> do not do certain things when there is a mate score

- evaluation.cpp
- evaluation.h
- perft.cpp
- position.cpp
- position.h
- search.cpp
> Reformatting

- search.cpp
```
ELO   | 0.63 +- 2.60 (95%)
LLR   | -2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 36816 W: 9930 L: 9863 D: 17023
```
Bench: 12327649
> reduce more when failing

- bitboard.cpp
- see.cpp
- see.h
- uci.cpp
```
ELO   | 36.13 +- 13.62 (95%)
GAMES | N: 1496 W: 521 L: 366 D: 609
https://chess.swehosting.se/test/2049/
```
> Better SEE

- evaluation.cpp
- move_ordering.cpp
- move_ordering.h
- search.cpp
> Bitboard rewrite

- evaluation.cpp
```
ELO   | 2.62 +- 4.04 (95%)
LLR   | 0.68 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 13656 W: 3345 L: 3242 D: 7069
https://chess.swehosting.se/test/2569/
```
Bench: 8968889
> Drawishness calculations improved

- src/search.cpp
```
ELO   | -1.97 +- 2.24 (95%)
LLR   | -0.40 (-2.25, 2.89) [-5.00, 0.00]
GAMES | N: 44240 W: 10537 L: 10788 D: 22915
https://chess.swehosting.se/test/4329/
```
Merged because it is a small loss that fixes ongoing issues in the engine of illogical and bad code.
> Capture move history score fixed

- src/nnue.cpp
- src/search.cpp
```
ELO   | 3.61 +- 2.92 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 27136 W: 6941 L: 6659 D: 13536
https://chess.swehosting.se/test/4511/
```
> Cont hist mhs

- src/datagen.cpp
- src/position.cpp
- src/position.h
- src/search.cpp
- src/uci.cpp
```
ELO   | 23.92 +- 10.30 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 5.00]
GAMES | N: 2080 W: 566 L: 423 D: 1091
https://chess.swehosting.se/test/5187/
```
> Nnue updates

- src/search.cpp
```
Elo   | 16.35 +- 9.14 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2552 W: 647 L: 527 D: 1378
Penta | [15, 250, 638, 346, 27]
http://antares2262.pythonanywhere.com/test/5/
```
Bench: 6847628
> change IIR with PV nodes

- src/move_ordering.cpp
- src/move_ordering.h
```
Elo   | 0.25 +- 2.87 (95%)
LLR   | -2.26 (-2.25, 2.89) [0.00, 5.00]
Games | N: 26548 W: 6271 L: 6252 D: 14025
Penta | [220, 3241, 6338, 3250, 225]
```
Merged for simplification and fixes, did not lose ELO.
Bench: 6459611
> Staged scoring efficiency changes and fixes

- src/move_ordering.cpp
- src/position.cpp
- src/position.h
- src/search.cpp
- src/search.h
```
Elo   | 5.87 +- 4.79 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 9880 W: 2504 L: 2337 D: 5039
Penta | [51, 1134, 2427, 1253, 75]
```
> Threat history

- src/position.cpp
- src/position.h
- src/search.cpp
- src/search.h
```
Elo   | 3.30 +- 3.25 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 4.00]
Games | N: 20922 W: 5113 L: 4914 D: 10895
Penta | [122, 2385, 5242, 2596, 116]
```
> Np corr hist

- src/position.cpp
- src/position.h
- src/search.cpp
- src/search.h
- src/types.h
```
Elo   | 6.84 +- 5.23 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 4.00]
Games | N: 8280 W: 2110 L: 1947 D: 4223
Penta | [48, 914, 2069, 1045, 64]
```
Bench: 7839952
> major piece correction history

- src/position.cpp
- src/position.h
- src/search.cpp
- src/search.h
- src/types.h
```
Elo   | 7.74 +- 5.71 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 4.00]
Games | N: 7008 W: 1805 L: 1649 D: 3554
Penta | [30, 767, 1762, 907, 38]
http://antares2262.pythonanywhere.com/test/242/
```
Bench: 6605220
> minor piece correction history
